# arxivの学問領域の指定
subject: 'cat:cs.CR'

# 検索キーワード
keywords:
        trustzone: 5
        tee: 5
        cortex-m: 4
        arm: 3
        container: 3
        docker: 3
        iot: 2

# 通知の閾値
score_threshold: 0
